# Generated by Django 5.2.4 on 2025-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_location_is_active_alter_reviewlike_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('park', 'Park'), ('shop', 'Shop'), ('museum', 'Museum')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
